[tool.poetry]
name = "lhp"
version = "0.1.0"
description = ""
authors = ["Lucius C. <58442255+czlucius@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
py-cord = "^2.0.0rc1"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
